version: '2'

services:
    elasticsearch:
        image: elasticsearch:5.5.1
        ports:
            - 9200:9200
            - 9300:9300
        volumes:
            - ${ELASTIC_DIR}:/usr/share/elasticsearch/data
    
    kibana:
        image: kibana:5.5.1
        ports:
            - 5601:5601
        environment:
            - ELASTICSEARCH_URL=http://elasticsearch:9200
    